/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{
    dashcode.setupParts();
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{
    // Stop any timers to prevent CPU usage
    // Remove any preferences as needed
    // widget.setPreferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    if (window.widget) {
        widget.setPreferenceForKey(null, "strong");
        widget.setPreferenceForKey(null, "length");
    }
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{
    // Restart any timers that were stopped on hide
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
        
        document.getElementById("strong").checked = isStrong();
        document.getElementById("length").value = minLength();
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }    
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}

function getLetter()
{
    var letter = (Math.floor(Math.random() * 26) + 10).toString(36);
    if (Math.random() > 0.5) {
        return letter.toUpperCase();
    } else {
        return letter;
    }
}
      
function getSpecial(strong)
{
    var selection = "!§$%&/()=?+*#-_^<>\\";
    if (strong) {
        selection += "€£¥@[]{},.;:´`^°ßâîêôûáíóéóúàìèòùÂÎÊÔÛÁÍÉÓÚÀÌÈÒÙžŽšŠãõñÃÕÑ¿¡¨®©ç¢Ç~œæŒÆøØëïöäüÿýÜÄÖÏÅËŸÝ";
    }
    return selection.charAt(Math.floor(Math.random()*selection.length));
}

function isStrong()
{
    if(window.widget) {
        var strongSetting = widget.preferenceForKey("strong");
        
        if (strongSetting) {
            return true;
        }
    }
    return false;
}

function minLength()
{
    if(window.widget) {
        var minLength = widget.preferenceForKey("length");
        if (minLength && minLength.length > 0) {
            return parseInt(minLength);
        }
    }
    return 12;
}


function generatePassword(event)
{
    widget.setPreferenceForKey(document.getElementById("strong").checked ? 1 : 0, "strong");
    widget.setPreferenceForKey(document.getElementById("length").value, "length");
    
    var strong = isStrong();
    var length = Math.round(minLength() * (1 + Math.random() * 0.4));
    var password = "";
    
    for (i = 0; i < length; ++i) {
        var chance = Math.random();
        if (chance > 0.85) {
            password += Math.floor(Math.random() * 10);
        } else if (chance > 0.5) {
            password += getSpecial(strong);
        } else {
            password += getLetter();
        }
    }
        
    document.getElementById('password').value = password;
    document.getElementById('lengthInfo').innerHTML = password.length;
}
